org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Flutter configuration
flutter.compileSdkVersion=36
flutter.targetSdkVersion=36
flutter.minSdkVersion=24
flutter.ndkVersion=28.2.13676358
flutter.versionCode=157
flutter.versionName=1.0.0+157