FROM python:3.9-slim

WORKDIR /app

COPY requirements-newsletter.txt .
RUN pip install -r requirements-newsletter.txt

COPY background_article_processor_service.py .

EXPOSE 5015

CMD ["python", "background_article_processor_service.py"]