FROM python:3.9-slim

WORKDIR /app

COPY requirements-newsletter.txt .
RUN pip install -r requirements-newsletter.txt

COPY simple_news_search_service.py .

EXPOSE 5016

CMD ["python", "simple_news_search_service.py"]