FROM python:3.9-slim
WORKDIR /app
COPY requirements_orchestrator.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY tour_orchestrator_service.py /app/
EXPOSE 5002
CMD ["python", "tour_orchestrator_service.py"]