#!/usr/bin/env python3
"""run_local533_cache_check.py — FREE verification: the tour generated by
run_local533_one_tour.py is now cached, so this request is a cache hit. A cache
hit issues no grounded requests and must report grounding $0.00.
Issues no paid API calls.
"""
import os
import sys
import json

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
for line in open(os.path.join(HERE, '.env')):
    line = line.strip()
    if line and not line.startswith('#') and '=' in line:
        k, v = line.split('=', 1)
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))
os.environ['STORIED_MODE'] = 'true'
os.environ['DISABLE_TOUR_CACHE'] = '0'
os.environ.setdefault('DATABASE_URL',
                      'postgresql://admin:password123@localhost:5433/audiotours')

import story_leads  # noqa: E402
from generate_tour_text import generate_tour_text  # noqa: E402
import generate_tour_text as _gtt  # noqa: E402

LOCATION = 'Our Lady Help of Christians Catholic Church, Newton MA'
text, _, _ = generate_tour_text(LOCATION, 'museum', HERE + '/_l533_cache.txt', 4)
c = dict(_gtt._LAST_GENERATION_COST or {})
print("\n_LAST_GENERATION_COST =", json.dumps(c, indent=2))
print("get_grounding_requests() =", story_leads.get_grounding_requests())

ok = (c.get('cache_hit') is True
      and c.get('grounding_requests', -1) == 0
      and abs(c.get('grounding_cost', 1.0)) < 1e-9
      and abs(c.get('tour_total_cost', 1.0)) < 1e-9
      and story_leads.get_grounding_requests() == 0)
print("\nRESULT:", "PASS — cache hit reports grounding $0.00 / 0 requests" if ok else "FAILED")
sys.exit(0 if ok else 1)
