#!/usr/bin/env python3
"""LOCAL-244: Prolog escapes gates — fix and verify.

The prolog is generated by a separate LLM call and injected into Stop 1
at assembly (D64), after every gate has run. LOCAL-244 adds PHASE 5.9:
R9, R10, and the subject routine applied to the prolog BEFORE injection.

This script:
  1. Generates a fresh 2-stop Riviera tour with prolog gating active
  2. Captures prolog before/after word counts and any deletions
  3. Runs R10 residual check on the DELIVERED text (including prolog)
  4. Overwrites RIVIERA_2STOP_ROUND3.md with the five-way comparison
  5. Reports honestly — if the prolog collapses, says so
"""
import os
import sys
import re
import io
import json
import time
import traceback

# --- Project root ---
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, PROJECT_ROOT)
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'tests'))

# --- Load .env for API keys (never hardcode) ---
_env_path = os.path.expanduser("~/Audioura/.env")
if os.path.exists(_env_path):
    with open(_env_path) as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _, _v = _line.partition('=')
                _k = _k.strip()
                _v = _v.strip().strip('"').strip("'")
                if _k and _k not in os.environ:
                    os.environ[_k] = _v

# --- Environment: ALL GATES ON ---
os.environ['STORIED_MODE'] = 'true'
os.environ['ENABLE_STOP_EXISTENCE_GATE'] = '1'

# Remove any disable flags — all gates live
for k in ('TOUR_LLM_MODEL', 'DISABLE_CORPUS_GATE', 'DISABLE_STOP_CORPUS',
           'DISABLE_STYLE_RETRY', 'DISABLE_R9_DELETION', 'DISABLE_R10_DELETION',
           'DISABLE_CONTRADICTED_BLOCK', 'DISABLE_SUBJECT_ROUTINE',
           'DISABLE_STOP_EXISTENCE_GATE'):
    if k in os.environ:
        del os.environ[k]

# Remove DATABASE_URL to bypass S20 tour cache (forces fresh generation)
_saved_db_url = os.environ.pop('DATABASE_URL', None)

# --- Imports ---
from db_connection import get_connection, check_db_available

EXPECTED_NICE = [1, 12, 14, 17, 24, 29, 152]

print("=" * 70)
print("LOCAL-244: PROLOG ESCAPES GATES — FIX AND VERIFY")
print("  All gates live incl. PHASE 5.9 (prolog gating: R9, R10, subject)")
print("  Cache BYPASSED (DATABASE_URL removed)")
print("  Model: gpt-3.5-turbo (default, TOUR_LLM_MODEL unset)")
print("=" * 70)

# --- Step 0: Pre-checks ---
if not check_db_available():
    print("FATAL: Database unreachable")
    sys.exit(7)

conn = get_connection()
cur = conn.cursor()
cur.execute("SELECT COUNT(*) FROM audio_tours")
count_before = cur.fetchone()[0]
print(f"[PRE] audio_tours row count: {count_before}")

cur.execute("""
    SELECT id FROM audio_tours
    WHERE is_test IS NOT TRUE
      AND lat IS NOT NULL AND lng IS NOT NULL
      AND lat BETWEEN 43.5 AND 43.9
      AND lng BETWEEN 7.0 AND 7.5
    ORDER BY id
""")
nice_rows_pre = [r[0] for r in cur.fetchall()]
visible_nice_pre = [i for i in nice_rows_pre if i in EXPECTED_NICE]
print(f"[PRE] Nice visible tour IDs: {visible_nice_pre}")
assert visible_nice_pre == EXPECTED_NICE, f"Nice list mismatch! Got {visible_nice_pre}"
conn.close()

# --- Step 1: Generate tour with prolog gating active ---
print("\n" + "-" * 70)
print("STEP 1: Generating 2-stop biking tour (all gates + PHASE 5.9 prolog gating)")
print("-" * 70)

from generate_tour_text import generate_tour_text, _LAST_GENERATION_COST

output_file = os.path.join(PROJECT_ROOT, "tours", "LOCAL244_riviera_2stop_prolog_gated.txt")

# Capture stdout to extract PHASE 5.9 log lines
_orig_stdout = sys.stdout
_captured = io.StringIO()


class TeeWriter:
    """Write to both captured buffer and original stdout."""
    def __init__(self, orig, buf):
        self.orig = orig
        self.buf = buf

    def write(self, s):
        self.orig.write(s)
        self.buf.write(s)

    def flush(self):
        self.orig.flush()
        self.buf.flush()


sys.stdout = TeeWriter(_orig_stdout, _captured)

start_time = time.time()
try:
    result = generate_tour_text(
        location="French Riviera cycling tour, France",
        tour_type="biking",
        output_file=output_file,
        total_stops=2,
        persona=None,
    )
except Exception as e:
    sys.stdout = _orig_stdout
    elapsed = time.time() - start_time
    print(f"FATAL: Generation failed after {elapsed:.1f}s: {e}")
    traceback.print_exc()
    # Restore LOCAL-243's document unchanged
    sys.exit(1)

sys.stdout = _orig_stdout
elapsed = time.time() - start_time
gen_log = _captured.getvalue()

if not result or not result[0]:
    print(f"FATAL: Tour generation returned None after {elapsed:.1f}s")
    sys.exit(1)

tour_text = result[0]
from generate_tour_text import _LAST_GENERATION_COST
gen_cost = _LAST_GENERATION_COST.copy()
print(f"\n  Generated: {len(tour_text)} chars, {len(tour_text.split())} words in {elapsed:.1f}s")
print(f"  Cost: ${gen_cost.get('total_cost', 0):.4f}")
print(f"  Tokens: {gen_cost.get('total_tokens', 0)}")

# Restore DATABASE_URL for DB operations
if _saved_db_url:
    os.environ['DATABASE_URL'] = _saved_db_url

# --- Step 1b: Extract PHASE 5.9 prolog gating results from log ---
print("\n" + "-" * 70)
print("STEP 1b: PHASE 5.9 (prolog gating) — LOG ANALYSIS")
print("-" * 70)

prolog_words_before = None
prolog_words_after = None
prolog_r9_deleted = 0
prolog_r10_deleted = 0
prolog_subject_expanded = 0
prolog_subject_deleted = 0
prolog_subject_cost = 0.0
prolog_deletions_verbatim = []
prolog_collapsed = False
prolog_gating_ran = False

_in_prolog_deletions_section = False
for line in gen_log.split('\n'):
    if '[LOCAL-244]' in line:
        prolog_gating_ran = True
    if 'Prolog deletions' in line and '[LOCAL-244]' in line:
        _in_prolog_deletions_section = True
    elif '[LOCAL-244]' in line and 'Prolog deletions' not in line and 'Prolog' in line:
        _in_prolog_deletions_section = False
    elif 'DEBUG - POI' in line or 'PHASE' in line:
        _in_prolog_deletions_section = False
    if 'Prolog before gates:' in line:
        m = re.search(r'(\d+) words', line)
        if m:
            prolog_words_before = int(m.group(1))
    if 'Prolog after gates:' in line:
        m = re.search(r'(\d+) words', line)
        if m:
            prolog_words_after = int(m.group(1))
    if 'Prolog R9:' in line and 'deleted' in line:
        m = re.search(r'(\d+) sentence', line)
        if m:
            prolog_r9_deleted = int(m.group(1))
    if 'Prolog R10:' in line and 'deleted' in line:
        m = re.search(r'(\d+) sentence', line)
        if m:
            prolog_r10_deleted = int(m.group(1))
    if 'Prolog subject:' in line:
        m = re.search(r'(\d+) expanded', line)
        if m:
            prolog_subject_expanded = int(m.group(1))
        m = re.search(r'(\d+) deleted', line)
        if m:
            prolog_subject_deleted = int(m.group(1))
        m = re.search(r'cost=\$([0-9.]+)', line)
        if m:
            prolog_subject_cost = float(m.group(1))
    if 'WARNING: Prolog collapsed' in line:
        prolog_collapsed = True
    # Capture verbatim deletion lines (indented under [LOCAL-244] Prolog deletions)
    if _in_prolog_deletions_section and ('R9_GENERIC' in line or 'R10_UNFULFILLED' in line or 'SUBJECT_DELETED' in line):
        m = re.search(r'\[(R9_GENERIC|R10_UNFULFILLED_PROMISE|SUBJECT_DELETED)\]\s*"(.+)"', line)
        if m:
            prolog_deletions_verbatim.append((m.group(1), m.group(2).rstrip('"').rstrip('.')))

print(f"  PHASE 5.9 ran: {prolog_gating_ran}")
print(f"  Prolog words before: {prolog_words_before}")
print(f"  Prolog words after:  {prolog_words_after}")
print(f"  R9 deletions:  {prolog_r9_deleted}")
print(f"  R10 deletions: {prolog_r10_deleted}")
print(f"  Subject expanded: {prolog_subject_expanded}")
print(f"  Subject deleted:  {prolog_subject_deleted}")
print(f"  Subject cost: ${prolog_subject_cost:.4f}")
print(f"  Prolog collapsed: {prolog_collapsed}")
if prolog_deletions_verbatim:
    print(f"  Verbatim deletions:")
    for rule, sent in prolog_deletions_verbatim:
        print(f"    [{rule}] \"{sent[:100]}\"")

# Also extract R10 in-pipeline results
r10_in_pipeline = False
r10_pipeline_deleted = 0
for line in gen_log.split('\n'):
    if 'PHASE 5.155: R10 unfulfilled-promise deletion' in line:
        r10_in_pipeline = True
    if 'R10 summary:' in line and 'LOCAL-235' in line:
        m = re.search(r'(\d+) sentences? deleted', line)
        if m:
            r10_pipeline_deleted = int(m.group(1))

print(f"\n  R10 in-pipeline (stops): ran={r10_in_pipeline}, deleted={r10_pipeline_deleted}")

# --- Step 2: Parse stops + verify existence ---
print("\n" + "-" * 70)
print("STEP 2: Parse Stops + Existence Verification")
print("-" * 70)

from stop_anchor_detector_v2 import parse_tour_stops
from corpus_coverage import assess_stop_coverage
from stop_corpus_reader import get_stop_corpus_for_tour
from stop_existence_gate import verify_stop_existence

stops = parse_tour_stops(tour_text)
print(f"  Parsed {len(stops)} stops:")
for s in stops:
    print(f"    - {s['title']} ({len(s.get('paragraphs', []))} paragraphs)")

stop_names = [s['title'] for s in stops]

conn = get_connection()
corpus_data = get_stop_corpus_for_tour("French Riviera", stop_names, conn)

coverage_verdicts = {}
existence_verdicts = {}

for stop_name in stop_names:
    sc = corpus_data.get(stop_name)
    if sc and sc.get('passages'):
        assessment = assess_stop_coverage(
            stop_name, "French Riviera", sc['passages'],
            passage_roles=sc.get('passage_roles')
        )
        coverage_verdicts[stop_name] = assessment['verdict']
    else:
        coverage_verdicts[stop_name] = "NO_CORPUS"

    ev = verify_stop_existence(stop_name, "French Riviera walking area", conn)
    existence_verdicts[stop_name] = ev
    status = 'VERIFIED' if ev.get('verified') else 'UNVERIFIED'
    print(f"    {stop_name}: coverage={coverage_verdicts[stop_name]}, "
          f"existence={status} (kind={ev.get('venue_kind')})")
conn.close()

# --- Step 3: Subject validate/expand/remove on stop paragraphs ---
print("\n" + "-" * 70)
print("STEP 3: Subject Validate -> Expand -> Remove (stops)")
print("-" * 70)

from subject_validate_expand import process_paragraph, is_subject_routine_enabled
print(f"  Subject routine enabled: {is_subject_routine_enabled()}")

conn = get_connection()
subject_results = []
total_promises = 0
total_expanded = 0
total_deleted = 0
subject_cost = 0.0

processed_stops = []
for stop_idx, stop in enumerate(stops):
    stop_title = stop['title']
    is_verified = existence_verdicts.get(stop_title, {}).get('verified', False)
    paragraphs = stop.get('paragraphs', [])
    processed_paragraphs = []

    for para_idx, para in enumerate(paragraphs):
        para_text = para.strip()
        if not para_text:
            processed_paragraphs.append(para_text)
            continue
        sr = process_paragraph(
            paragraph=para_text,
            stop_title=stop_title,
            venue_name="French Riviera cycling tour",
            conn=conn,
            existence_verified=is_verified,
        )
        subject_cost += sr['cost']
        total_promises += len(sr['promises_found'])
        total_expanded += sr['expanded_count']
        total_deleted += sr['deleted_count']

        for p in sr['promises_found']:
            subject_results.append({
                'stop': stop_title,
                'para_idx': para_idx + 1,
                'sentence': p['sentence'],
                'outcome': p['outcome'],
                'expansion': p.get('expansion'),
                'reason': p.get('reason'),
            })

        if sr['expanded_count'] > 0 or sr['deleted_count'] > 0:
            print(f"    [{stop_title}] Para {para_idx+1}: +{sr['expanded_count']} expanded, "
                  f"-{sr['deleted_count']} deleted")
            processed_paragraphs.append(sr['processed'])
        else:
            processed_paragraphs.append(para_text)

    processed_stops.append({'title': stop_title, 'paragraphs': processed_paragraphs})
conn.close()

print(f"\n  SUBJECT ROUTINE (stops): promises={total_promises}, expanded={total_expanded}, "
      f"deleted={total_deleted}, cost=${subject_cost:.4f}")

# --- Step 4: R10 residual check on DELIVERED text (including prolog) ---
print("\n" + "-" * 70)
print("STEP 4: R10 Residual Check on DELIVERED text (stops + prolog)")
print("-" * 70)

import importlib.util
_svd_spec = importlib.util.spec_from_file_location(
    "style_validator_detector_root",
    os.path.join(PROJECT_ROOT, "style_validator_detector.py")
)
_svd_mod = importlib.util.module_from_spec(_svd_spec)
_svd_spec.loader.exec_module(_svd_mod)
validate_paragraph = _svd_mod.validate_paragraph

try:
    apply_r10 = _svd_mod.apply_r10_to_description
except AttributeError:
    apply_r10 = None

try:
    apply_r9 = _svd_mod.apply_r9_to_description
except AttributeError:
    apply_r9 = None

r10_residual_deletions = []
r10_residual_count = 0
if apply_r10:
    for stop in processed_stops:
        full_desc = '\n\n'.join(p for p in stop['paragraphs'] if p.strip())
        _new_desc, _deleted, _emptied = apply_r10(full_desc)
        if _deleted > 0:
            r10_residual_count += _deleted
            old_sentences = set()
            for p in full_desc.split('\n\n'):
                for s in re.split(r'(?<=[.!?])\s+', p):
                    if s.strip():
                        old_sentences.add(s.strip())
            new_sentences_set = set()
            for p in _new_desc.split('\n\n'):
                for s in re.split(r'(?<=[.!?])\s+', p):
                    if s.strip():
                        new_sentences_set.add(s.strip())
            for s in old_sentences:
                if s not in new_sentences_set:
                    r10_residual_deletions.append({'stop': stop['title'], 'sentence': s})

    if r10_residual_deletions:
        print(f"  R10 residual: {r10_residual_count} sentence(s) STILL trigger R10")
        for d in r10_residual_deletions:
            print(f"    [{d['stop']}] \"{d['sentence'][:80]}...\"")
    else:
        print(f"  R10 residual: 0 — delivered text is clean")
else:
    print("  WARNING: apply_r10_to_description not available")

# --- Step 5: Style analysis ---
print("\n" + "-" * 70)
print("STEP 5: Final Style Analysis")
print("-" * 70)

para_styles = []
para_word_counts = []
for stop in processed_stops:
    for pidx, para in enumerate(stop['paragraphs']):
        if not para.strip():
            continue
        wc = len(para.split())
        sr = validate_paragraph(para)
        rules = sr.get('rules_violated', set())
        style_str = ','.join(sorted(rules)) if rules else 'clean'
        para_styles.append({'stop': stop['title'], 'para_idx': pidx + 1,
                           'style': style_str, 'words': wc})
        para_word_counts.append(wc)
        print(f"  [{stop['title']}] Para {pidx+1}: {wc}w {style_str}")

total_words = sum(para_word_counts)
print(f"\n  Total words: {total_words}")

# --- Step 6: Store in DB ---
print("\n" + "-" * 70)
print("STEP 6: Store in DB (is_test=true, lat/lng=NULL)")
print("-" * 70)

final_text_parts = []
for stop in processed_stops:
    final_text_parts.append(f"## {stop['title']}\n")
    for p in stop['paragraphs']:
        if p.strip():
            final_text_parts.append(p.strip())
            final_text_parts.append("")
final_tour_text = '\n\n'.join(final_text_parts).strip()

conn = get_connection()
cur = conn.cursor()
cur.execute("""
    INSERT INTO audio_tours (
        tour_name, request_string, number_requested,
        is_test, storied_mode, tour_content, stops_count,
        lat, lng
    )
    VALUES (%s, %s, %s, %s, %s, %s, %s, NULL, NULL)
    RETURNING id
""", (
    f'French Riviera Cycling [LOCAL-244 Prolog Gated {time.strftime("%H%M%S")}]',
    'French Riviera cycling tour, France',
    2,
    True,
    True,
    tour_text,
    len(stops),
))
new_tour_id = cur.fetchone()[0]
conn.commit()

cur.execute("SELECT COUNT(*) FROM audio_tours")
count_after = cur.fetchone()[0]

cur.execute("""
    SELECT id FROM audio_tours
    WHERE is_test IS NOT TRUE
      AND lat IS NOT NULL AND lng IS NOT NULL
      AND lat BETWEEN 43.5 AND 43.9
      AND lng BETWEEN 7.0 AND 7.5
    ORDER BY id
""")
nice_rows_post = [r[0] for r in cur.fetchall()]
visible_nice_post = [i for i in nice_rows_post if i in EXPECTED_NICE]
conn.close()

print(f"  Stored as tour_id={new_tour_id} (is_test=true, lat=NULL, lng=NULL)")
print(f"  audio_tours: {count_before} -> {count_after} (delta: +{count_after - count_before})")
print(f"  Nice list: {visible_nice_post}")
assert visible_nice_post == EXPECTED_NICE, f"Nice list CHANGED! Got {visible_nice_post}"
print(f"  Nice list UNCHANGED ✓")

# --- Step 7: Build RIVIERA_2STOP_ROUND3.md ---
print("\n" + "-" * 70)
print("STEP 7: Building RIVIERA_2STOP_ROUND3.md")
print("-" * 70)

md = []
md.append("# French Riviera Cycling Tour - 2 Stops, Round 3 (LOCAL-244)")
md.append("")
md.append("**End-to-end regeneration with prolog gating active (PHASE 5.9).**")
md.append("")
md.append(f"> Total words: **{total_words}** (round 2 was 819).")
md.append("")

# Summary table
md.append("## Summary Table")
md.append("")
md.append("| Field | Value |")
md.append("|---|---|")
md.append(f"| gates active | stop-existence, subject routine, **R10**, R9, CONTRADICTED, style retry, **PHASE 5.9 prolog gating** |")
md.append(f"| model | gpt-3.5-turbo (default) |")
total_cost = gen_cost.get('total_cost', 0) + subject_cost + prolog_subject_cost
md.append(f"| cost | ${total_cost:.4f} (generation ${gen_cost.get('total_cost', 0):.4f} + subject ${subject_cost + prolog_subject_cost:.4f}) |")
md.append(f"| tokens | {gen_cost.get('total_tokens', 0)} |")
md.append(f"| cache hit | {gen_cost.get('cache_hit', False)} |")
if stops:
    md.append(f"| stops selected | {', '.join(stop_names)} |")
    for sn in stop_names:
        ev = existence_verdicts.get(sn, {})
        cv = coverage_verdicts.get(sn, 'UNKNOWN')
        status = 'VERIFIED' if ev.get('verified') else 'UNVERIFIED'
        md.append(f"| -> {sn} | {status} - {cv} |")
md.append(f"| promises found (subject, stops) | {total_promises} |")
md.append(f"| expanded (stops) | {total_expanded} |")
md.append(f"| deleted (subject, stops) | {total_deleted} |")
md.append(f"| **prolog words before gates** | **{prolog_words_before}** |")
md.append(f"| **prolog words after gates** | **{prolog_words_after}** |")
md.append(f"| **prolog R9 deletions** | **{prolog_r9_deleted}** |")
md.append(f"| **prolog R10 deletions** | **{prolog_r10_deleted}** |")
md.append(f"| **prolog subject expanded** | **{prolog_subject_expanded}** |")
md.append(f"| **prolog subject deleted** | **{prolog_subject_deleted}** |")
md.append(f"| **prolog collapsed** | **{prolog_collapsed}** |")
md.append(f"| R10 in-pipeline (stops) deletions | {r10_pipeline_deleted} |")
md.append(f"| R10 residual in delivered text | {r10_residual_count} |")
md.append(f"| generation time | {elapsed:.1f}s |")
md.append(f"| date | {time.strftime('%Y-%m-%d %H:%M')} |")
md.append(f"| tour ID | {new_tour_id} (is_test=true) |")
md.append("")

# Word counts table
md.append("## Word Counts")
md.append("")
md.append("| Paragraph | Stop | Words | Style |")
md.append("|---|---|---|---|")
for ps in para_styles:
    md.append(f"| P{ps['para_idx']} | {ps['stop']} | {ps['words']} | {ps['style']} |")
md.append(f"| **Total** | | **{total_words}** | |")
md.append(f"| Round 2 | | 819 | |")
md.append("")

# Five-way comparison
md.append("## Five-Way Word Count Comparison")
md.append("")
md.append("```")
md.append("Run                               Words   R10 position")
md.append("------------------------------ --------   --------------------")
md.append("Round 2                             819   (no R10)")
md.append("LOCAL-240 re-applied                191   (R10 on old text)")
md.append("LOCAL-241 end-to-end                393   (R10 post-processing)")
md.append("LOCAL-243 (R10 in-pipeline)         505   (R10 in-pipeline)")
md.append(f"LOCAL-244 (this run)               {total_words:4d}   (R10 in-pipeline + prolog gated)")
md.append("```")
md.append("")

# Prolog section
md.append("## Prolog Gating (LOCAL-244 — PHASE 5.9)")
md.append("")
md.append(f"**Prolog word count before gates:** {prolog_words_before}")
md.append(f"**Prolog word count after gates:** {prolog_words_after}")
delta = (prolog_words_after or 0) - (prolog_words_before or 0)
md.append(f"**Delta:** {delta} words")
md.append("")

if prolog_deletions_verbatim:
    md.append("### Prolog Deletions (verbatim)")
    md.append("")
    for rule, sent in prolog_deletions_verbatim:
        md.append(f"- **[{rule}]** *\"{sent}\"*")
    md.append("")
else:
    md.append("### Prolog Deletions")
    md.append("")
    md.append("None — prolog survived all gates intact.")
    md.append("")

if prolog_collapsed:
    md.append("### ⚠️ PROLOG COLLAPSE WARNING")
    md.append("")
    md.append(f"The prolog collapsed from {prolog_words_before} to {prolog_words_after} words.")
    md.append("This is the same finding as the stop-level collapses: the LLM produces")
    md.append("promise-language that gates correctly remove, but no underlying content remains.")
    md.append("")

# Full tour text
md.append("---")
md.append("")
md.append("## End-to-End Tour (generated text after all gates)")
md.append("")

for stop_idx, stop in enumerate(processed_stops):
    md.append(f"### {stop['title']}")
    md.append("")
    ev = existence_verdicts.get(stop['title'], {})
    cv = coverage_verdicts.get(stop['title'], 'UNKNOWN')
    md.append(f"**Existence:** {'VERIFIED' if ev.get('verified') else 'UNVERIFIED'} ({ev.get('venue_kind', '?')})")
    md.append(f"**Coverage:** {cv}")
    md.append("")
    for pidx, para in enumerate(stop['paragraphs']):
        if not para.strip():
            continue
        wc = len(para.split())
        style_info = next((ps for ps in para_styles
                          if ps['stop'] == stop['title'] and ps['para_idx'] == pidx + 1), None)
        style_str = style_info['style'] if style_info else '?'
        md.append(f"#### Paragraph {pidx + 1} ({wc} words)")
        md.append("")
        md.append(para.strip())
        md.append("")
        md.append(f"`[style: {style_str}]`")
        md.append("")

# R10 residual
md.append("---")
md.append("")
md.append("## R10 Residual Check (on delivered text)")
md.append("")
md.append(f"**R10 residual sentences in delivered text: {r10_residual_count}**")
md.append("")
if r10_residual_deletions:
    for d in r10_residual_deletions:
        md.append(f"- [{d['stop']}] *\"{d['sentence']}\"*")
    md.append("")
else:
    md.append("Delivered text is clean — 0 R10 triggers remain.")
    md.append("")

# Run summary
md.append("---")
md.append("")
md.append("## Run Summary")
md.append("")
md.append(f"- Tour ID: {new_tour_id} (is_test=true, lat/lng=NULL)")
md.append(f"- audio_tours: {count_before} -> {count_after} (delta: +{count_after - count_before})")
md.append(f"- Nice list: {visible_nice_post} - UNCHANGED")
md.append(f"- Model: gpt-3.5-turbo (TOUR_LLM_MODEL unset)")
md.append(f"- Total cost: ${total_cost:.4f}")
md.append(f"- Generation time: {elapsed:.1f}s")
md.append(f"- Total words (final): {total_words}")
md.append(f"- Prolog gating (PHASE 5.9): R9={prolog_r9_deleted} del, R10={prolog_r10_deleted} del, "
           f"subject={prolog_subject_expanded} exp/{prolog_subject_deleted} del")
md.append(f"- R10 in-pipeline (stops): {r10_pipeline_deleted} deletions")
md.append(f"- R10 residual: {r10_residual_count}")

md_content = '\n'.join(md) + '\n'

md_path = os.path.join(PROJECT_ROOT, "RIVIERA_2STOP_ROUND3.md")
with open(md_path, 'w') as f:
    f.write(md_content)
print(f"  Written: {md_path} ({len(md_content)} chars)")

# --- Final summary ---
print("\n" + "=" * 70)
print("LOCAL-244 COMPLETE")
print("=" * 70)
print(f"  Tour ID: {new_tour_id}")
print(f"  Total words: {total_words}")
print(f"  Prolog: {prolog_words_before}w -> {prolog_words_after}w "
      f"(R9={prolog_r9_deleted}, R10={prolog_r10_deleted}, "
      f"subj +{prolog_subject_expanded}/-{prolog_subject_deleted})")
print(f"  R10 residual in delivered text: {r10_residual_count}")
print(f"  audio_tours: {count_before} -> {count_after}")
print(f"  Nice list: UNCHANGED")
print(f"  Cost: ${total_cost:.4f}")
if prolog_collapsed:
    print(f"  ⚠️  PROLOG COLLAPSED — see RIVIERA_2STOP_ROUND3.md")
print("=" * 70)
