name: audio_tour_app_dev
description: AudioTours Dev - AI-powered audio tour generator
publish_to: 'none'
version: 1.2.6+396

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  archive: ^3.4.9
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.0.1
  geolocator: ^13.0.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.2
  flutter_volume_controller: ^1.3.2
  speech_to_text: ^7.0.0
  flutter_sound: ^9.2.13
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/